### ISSUE TITLE
make query parameter in select2 configurable (to prevent overlap with PageParameters)

### ISSUE THREAD

**Issue by d2a-raudenaerde** [wicketstuff/core#563] opened 2016-11-22 08:37 UTC
I have a set of PageParameters for my page, one is q (for query). This allows for nice URLs like:

http://myapplication/search?q=myquery.

But when I have a wicket-select2 component on my page, it initializes the query for the select2 with the same value of the PageParameter q.

This causes the select2 to return an empty list of options, while the user has not even select anything yet.

Please add the query-parameter-name to the settings, so this overlap can be avoided.

**Comment by martin-g** [comment] 2016-11-22 08:39
:+1: 
Pull Request please!

**Comment by martin-g** [comment] 2016-11-22 08:40
OK. @solomax is on it!

**Comment by solomax** [comment] 2016-11-22 08:40
Will try to handle it tonight, should'n be rocket science :)

**Comment by solomax** [comment] 2016-11-22 14:28
Hello @reiern70, I need help :)))
To implement this I need to remove `static` modifier from AbstractSelect2Choice:generateJSON, but it seems to be currently impossible :( due to JsonResourceReference ....

**Comment by reiern70** [comment] 2016-11-22 14:40
why do you need to remove the static?

**Comment by solomax** [comment] 2016-11-22 14:42
It seems you are correct, I can avoid removing static
Will ask you to review the changes :)
Sorry for the noise :)

**Comment by reiern70** [comment] 2016-11-22 14:54
No problem.

**Comment by solomax** [comment] 2016-11-22 14:57
Here is the commit: https://github.com/wicketstuff/core/commit/c8f4b872a7fbdfa33993840ff5b6a78cac41be24
I'm afraid right now `stateless`, `mountPath` and `queryParam` might be out-of-sync at the moment
Should we add some additional consistency checks?

**Comment by reiern70** [comment] 2016-11-22 15:14
I think it should work. I cannot try it now but later today I can try the example

**Comment by solomax** [comment] 2016-11-22 15:41
It will work unless code like this will be used:

```
	Select2MultiChoice<CategoryTranslation> c = new Select2MultiChoice<CategoryTranslation>("categories", new PropertyModel<Collection<CategoryTranslation>>(searchBean, "translations"), CategoriesTextChoiceProvider.getInstance());
	c.getSettings()
		.setStateless(true)
		.setQueryParam("qq")
		.setMountPath(Application.CATEGORIES_JSON);
```

**Comment by reiern70** [comment] 2016-11-22 15:45
This last one failed? I think stateless => AJAX so query parameter will be qq... But I do not have the code in an IDE in from of me so I might be wrong.

**Comment by reiern70** [comment] 2016-11-22 15:48
I will try it tonight and comment back.

**Comment by solomax** [comment] 2016-11-22 15:48
According to https://github.com/wicketstuff/core/blob/master/select2-parent/select2/src/main/java/org/wicketstuff/select2/JsonResourceReference.java#L59

default `q` parameter will be used for JsonRef, and `qq` will be used while reading param values

OK thanks!

**Comment by reiern70** [comment] 2016-11-22 19:55
@solomax 

Using ResourceReferences is not very DRYish. We could do maybe

1- https://github.com/wicketstuff/core/blob/master/select2-parent/select2/src/main/java/org/wicketstuff/select2/JsonResourceReference.java#L50

add a constructor accepting parameter name. By default this is d

2- We modify static method 

AbstractSelect2Choice.generateJSON(getChoiceProvider(), webResponse);

To receive this parameter name (by default q).

**Comment by solomax** [comment] 2016-11-23 03:19
@reiern70 
2) is already implemented: https://github.com/wicketstuff/core/blob/c8f4b872a7fbdfa33993840ff5b6a78cac41be24/select2-parent/select2/src/main/java/org/wicketstuff/select2/AbstractSelect2Choice.java#L351

The issue is API allows user to "shoot in the foot", is it OK?
Or should it be documented? Or should some checks be added?

**Comment by reiern70** [comment] 2016-11-23 07:12
@solomax 

As said this way to use component is not very DRY: now it can  happen the same if you don't handle properly mount path. One ideal solution would be to mount resources on the fly: stateless selected mount some resource based on configuration. E.g. We have a generic JsonResourceHolderResource mounted at APP level (e.g. on path /sselect2) and component check if there is something able to handle the path it needs (e.g. cities) and if not mount it... on "select2/cities". But that could create other kind of problems as well.

**Comment by solomax** [comment] 2016-11-23 07:42
OK, let it be as-is for now, will merge to master and close, Thanks for reviewing!

**Comment by d2a-raudenaerde** [comment] 2016-11-23 07:43
Thanks all for the quick solution!

**Comment by solomax** [comment] 2016-11-23 07:59
Merged!
Please re-open in case fix is incomplete :)

**Closed by solomax** 2016-11-23 07:59 UTC
Labels: improvement
