### ISSUE TITLE
It's not possible to clear input in wicketstuff-select2 without touching a model

### ISSUE THREAD

**Issue by PhantomYdn** [wicketstuff/core#429] opened 2015-10-30 22:44 UTC
Please find a project which demonstrate this bug here: https://github.com/PhantomYdn/wicket-bugs/tree/master/wicketstuff-select2

If you will try to clear input: it will be replaced by initial value.

**Comment by solomax** [comment] 2015-10-31 03:35
duplicate of #411

**Comment by PhantomYdn** [comment] 2015-10-31 04:57
Might be... I tried to figure out: but no success. Thanks for attempting to fix that! Are you maintainer of this module? It's becoming quite important for our [datawarehouse](http://orienteer.org)

**Comment by solomax** [comment] 2015-10-31 04:58
I try to keep it alive, we also using it :(

**Comment by solomax** [comment] 2015-10-31 05:22
I propose to close these issues for now (#430, #429), and continue discussion in #411

**Comment by martin-g** [comment] 2015-10-31 06:32
Closing in favour of #411

**Comment by PhantomYdn** [comment] 2015-10-31 06:43
Issue checked on 7.2.0-SNAPSHOT. it's still there.

**Comment by solomax** [comment] 2015-11-01 06:33
looking at it, found an issue in value interpretation, but clear works as expected
will check-in new version today

**Comment by solomax** [comment] 2015-11-01 06:49
just commited improved version, ajax example is added and works as expected
please provide quick start if still an issue for you

**Comment by PhantomYdn** [comment] 2015-11-01 07:15
Project for quick start was referenced at the beginning.

**Comment by solomax** [comment] 2015-11-01 07:17
this project was based on broken select2 (incomplete fix for #411)
please check latest select2, especially ajax example

**Comment by PhantomYdn** [comment] 2015-11-01 09:35
Updated the following project: https://github.com/PhantomYdn/wicket-bugs/tree/master/wicketstuff-select2-71
It's on 7.2.0-SNAPSHOT

**Comment by solomax** [comment] 2015-11-02 02:15
Actually it seems to not Select2 issue
your AjaxFormSubmitBehavior does not submit the form, this is why model is not being changed
to ensure please add normal submit button 

I have no time to dig into this :(, maybe someone else can help

**Comment by PhantomYdn** [comment] 2015-11-02 03:55
It worked before 7.0. The idea is the following: update server when entry changed - and that's working perfectly if there are more than one input. But when it's cleared: value returned to initial model value.

So issue is there: please keep it open. I will try to fix it by myself.

**Comment by solomax** [comment] 2015-11-02 04:25
I'll try it one more time
The Form is not being submitted on 'change' event, I have added TextField component and it's model is not changed
This code [1] seems to work as expected
According to above there is nothing to fix in select2, it might be wicket issue, or maybe misuse

[1] https://github.com/wicketstuff/core/blob/master/select2-parent/select2-examples/src/main/java/org/wicketstuff/select2/HomePage.java#L77

**Comment by PhantomYdn** [comment] 2015-11-02 06:20
Issue is in transmitting empty value to a server side and especially in method Select2MultiChoice.getInputAsArray() it returns new String[0] which, actually, then transformed by FormComponent.inputChanged() to NO_RAW_INPUT and finally model value has been used instead of manually entered into the component.

**Comment by solomax** [comment] 2015-11-02 06:39
Have you tried the example from select2-examples?
Is it works for you?

**Comment by PhantomYdn** [comment] 2015-11-02 06:46
Those examples doesn't cover required case. In provided project "inputValue" updated without changing a model. But this case is pretty popular in real systems: for example when form should be slightly changed if some specific value was selected - so model shouldn't be updated, but current value has been used for calculation of visibility of some other component.

**Comment by solomax** [comment] 2015-11-02 06:49
OK, so it is misunderstanding
I thought the problem is in Model not being changed
Will try to take a look by the end of the week

**Comment by solomax** [comment] 2015-11-12 07:27
@martin-g sorry bothering, is there any way to determine if component value was modified or just initially displayed?

**Comment by martin-g** [comment] 2015-11-12 07:31
I'm not sure I fully understand the question.
Maybe you can use the ModelComparator [1] ?

1. https://github.com/apache/wicket/blob/4d18b76a6d8500c9b9047997b46ee8f55dd0fc9d/wicket-core/src/main/java/org/apache/wicket/Component.java#L3079

**Comment by solomax** [comment] 2015-11-12 07:35
The requirement is tricky
Model is not being changed by user action, but input value is changed
And currently model value is being used in case input value is empty (I have added the example with commit 70ef75d)

**Comment by martin-g** [comment] 2015-11-12 08:37
FormComponents have two model objects - the model object from the Component and the input.
Initially they are rendered by using the real model object. After form submit the input comes to the picture. 
Here is the flow:
1) formComponent#inputChanged()
2) formComponent#validate() - this executes the convertor and all validators 
3) if 2) is successful then store the converted input into the model object slot
4) if 2) is not successful then re-render by using the input as a value (this way the user should just fix the problem, and not re-type everything again)

I'll be able to take a look at the example later today. What should I look for?

**Comment by solomax** [comment] 2015-11-12 08:44
This [1] method is being used to draw the value
Actually I was sure converted input will go to the model object after change, but unfortunately this is not the case :(
input value is being changed, can be processed in ajax handler, but model is not changed
to ensure you can check 4th dropdown in select2-examples

[1] https://github.com/wicketstuff/core/blob/master/select2-parent/select2/src/main/java/org/wicketstuff/select2/AbstractSelect2Choice.java#L212

**Comment by martin-g** [comment] 2015-11-13 19:31
Hi Maxim,

I've added a comment to https://github.com/wicketstuff/core/commit/70ef75dcad67615aac5567f9931bb6be0227d95d#commitcomment-14389606.
In my opinion this is the problem.
If there is still a problem then please give more detailed explanation what is expected.
It is really hard for me to understand the purpose of this example. It is very similar to another one above that uses AjaxFormComponentUpdatingBehavior.

**Comment by martin-g** [comment] 2015-11-13 20:06
> Those examples doesn't cover required case. In provided project "inputValue" updated without changing a model. But this case is pretty popular in real systems: for example when form should be slightly changed if some specific value was selected - so model shouldn't be updated, but current value has been used for calculation of visibility of some other component.

Which other Wicket component/widget supports this use case?

**Comment by PhantomYdn** [comment] 2015-11-13 20:31
Previous version of select2 for support this.

**Comment by martin-g** [comment] 2015-11-13 21:56
Please find it!
Because I don't remember :-/

**Comment by PhantomYdn** [comment] 2015-11-14 05:45
For example this one: https://issues.apache.org/jira/browse/WICKET-5708

Generally speaking, ability to modify form according to data just being entered is a cool feature of Wicket. We use it widely in [Orienteer](https://github.com/OrienteerDW/Orienteer). In this particular issue: everything is fine except moment when you clear initial input. You can check that in [my example](https://github.com/PhantomYdn/wicket-bugs/tree/master/wicketstuff-select2-71): there 2 labeles to show model value and entered value.

**Comment by solomax** [comment] 2015-11-17 09:23
@martin-g I guess I'm not good enough to address this one :( Could you please handle it? I can help in testing :))

**Comment by ceefour** [comment] 2016-01-15 08:50
:+1:

**Comment by PhantomYdn** [comment] 2016-01-18 05:51
Just created pull-request for this: please see #454 
After this change everything is working for me as expected. Please, apply PR!

**Comment by ceefour** [comment] 2016-01-18 07:30
@phantomydn thank you! i hope this will make into 7.2

**Closed** 2016-01-23 08:57 UTC
