### ISSUE TITLE
Wicketstuff select2 7.1.0 simply doesn't work

### ISSUE THREAD

**Issue by PhantomYdn** [wicketstuff/core#430] opened 2015-10-30 22:51 UTC
Sample project to demonstrate the bug: https://github.com/PhantomYdn/wicket-bugs/tree/master/wicketstuff-select2-71

Screen shot : 
![wicketstuffselect271bug](https://cloud.githubusercontent.com/assets/1199285/10859781/16102d14-7f1e-11e5-81ca-c9242c9984a8.png)

As you can see: input is simply empty.

**Comment by solomax** [comment] 2015-10-31 02:45
Yes, it is my fault, i have reooened old issue and currently working on it

**Comment by solomax** [comment] 2015-10-31 03:35
duplicate of #411

**Comment by PhantomYdn** [comment] 2015-10-31 04:58
Are you sure that it's duplication? version 7.0 at least shown tokens

**Comment by solomax** [comment] 2015-10-31 05:10
yes, this is result of bad migration
currently working on it
you will get better version in ~30 minutes
then I need some time to fix tests, and some minor stuff

**Comment by solomax** [comment] 2015-10-31 05:22
I propose to close these issues for now (#430, #429), and continue discussion in #411 
working version is commited
could you please check if something still broken, will try to fix it with tests

**Comment by PhantomYdn** [comment] 2015-10-31 05:27
Ok - I will close. But how can I get new version? Will maven 7.2.0-SNAPSHOT work?

**Comment by martin-g** [comment] 2015-10-31 05:29
Better build it locally.

**Comment by solomax** [comment] 2015-10-31 05:31
select2-example works
I'll try to add more tests, and fix current tests
But be carefull the major API break is introduced with this upgrade :(

**Comment by PhantomYdn** [comment] 2015-10-31 06:23
I see changes in current git repository in master. Will test. But, btw, version in master is 7.1.0-SNAPSHOT instead of 7.2.0-SNAPSHOT. Is that correct?

**Comment by martin-g** [comment] 2015-10-31 06:32
Increased the version to 7.2.0-SNAPSHOT.
Thanks!

**Closed by martin-g** 2015-10-31 06:32 UTC

**Comment by PhantomYdn** [comment] 2015-10-31 06:43
It's almost work: tags actually stacked vertically. But first issue #429 is still there...

**Comment by solomax** [comment] 2015-10-31 07:26
what do you mean by "tags actually stacked vertically"?

**Comment by PhantomYdn** [comment] 2015-10-31 14:02
Previously, all was in one line. But now every new word placed underneath.

**Comment by solomax** [comment] 2015-11-01 06:50
please check select2-examples (can be tested using 'mvn jetty:run')
multiple countries are in one line, maybe css issue (setting wider width can help)?

**Comment by PhantomYdn** [comment] 2015-11-01 07:37
@martin-g increasing of version in main pom.xml didn't help... There are lots of projects underneath which are referencing to 7.1.0-SNAPSHOT parent - so their version remains the same: 7.1.0-SNAPSHOT.

**Comment by martin-g** [comment] 2015-11-01 09:56
Doh.
I'll be able to fix it this afternoon.
@solomax: please fix it if you have time earlier. Thanks!

**Comment by solomax** [comment] 2015-11-06 13:10
@martin-g updating versions right now

**Comment by solomax** [comment] 2015-11-06 13:14
done
hopefully the build will pass :)

**Comment by martin-g** [comment] 2015-11-06 21:00
Everything looks good!
Thank you!

**Comment by ceefour** [comment] 2016-01-15 08:51
Thanks @solomax @martin-g  :+1:
