### ISSUE TITLE
Update of markerclusterer.js reference

### ISSUE THREAD

**Issue by 2janci2** [wicketstuff/core#499] opened 2016-05-25 13:13 UTC
Google has changed the URL of the Marker Clusterer library (they moved to Git), from //google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer.js to this -> https://rawgit.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer.js in class GMapMarkerClustererHeaderContributor.java.

Every page using GMarkerCluster is not working properly since today.
Do you know about this?
Could you please update the reference ASAP?

Thank you.

**Comment by martin-g** [comment] 2016-05-25 13:16
Will do it as soon as you send a Pull Request!

**Comment by 2janci2** [comment] 2016-05-25 13:43
I sent a Pull Request, but it is my first time I did it, so I am not sure, if I did it well. I have noticed that there is tag 6.23.0 but core had only 6.19.0. 
Let me know ;-)

**Comment by 2janci2** [comment] 2016-05-30 13:24
Guys, have you noticed my last comment edit? Are you working on it?

**Comment by martin-g** [comment] 2016-05-30 13:32
Try by using non-minified version of this file. This will help you find out what is missing.
Hopefully it is some configuration issue.

**Comment by 2janci2** [comment] 2016-05-31 06:46
And how? Since that script is generated by the GMap somehow.

**Comment by JoachimRohde** [comment] 2016-05-31 13:55
Even though I couldn't reproduce any errors (beside the obvious one that it was not clustering, but nothing showed up in the console), I have locally a working solution. But I still need some time to clean up the code. (I guess I can squeeze this in within the next 24 hours).

@martin-g (or others who might have an answer): Do you have any experience with RawGit? The fact that they state on there website "The catch: this is a free service, so there are no uptime or support guarantees. " makes me believe that it would be better to include the clustering-script into the project (both are licenced under Apache, so no problem here). Any thoughts?

**Comment by martin-g** [comment] 2016-05-31 14:10
> it would be better to include the clustering-script into the project

Yes, I think this is better approach!

**Comment by JoachimRohde** [comment] 2016-06-01 12:15
I just pushed a fix, so that clustering should work again.
I haven't had the time yet to include the clustering-script into the project. I try to catch up on this on the weekend.

**Comment by JoachimRohde** [comment] 2016-06-03 13:57
I just included also the script (and necessary images) in the library.

**Closed by JoachimRohde** 2016-06-03 13:57 UTC
