### ISSUE TITLE
Upgrade Select2 to ver. 4.0

### ISSUE THREAD

**Issue by martin-g** [wicketstuff/core#411] opened 2015-05-26 11:35 UTC
Apparently Select2 has released its ver.4: https://github.com/select2/select2/releases
Maybe it is a good idea to upgrade the Wicket integration?!

**Comment by martin-g** [comment] 2015-05-26 11:35
@shuraa Are you interested?

**Comment by shuraa** [comment] 2015-05-26 14:38
Yep, but only for wicketstuff-7.x

**Comment by martin-g** [comment] 2015-05-26 14:39
Agreed!

**Comment by solomax** [comment] 2015-10-08 14:39
ok, will do :)

**Comment by solomax** [comment] 2015-10-09 11:17
it seems like 'drag-n-drop' functionality was dropped in 4.0 :( it's bad :(

**Comment by solomax** [comment] 2015-10-30 12:04
Select2 seems to be non-working after upgrade :( my bad
Will try to fix it ASAP

**Comment by PhantomYdn** [comment] 2015-10-31 21:50
Guys, #429 seems to be not a duplicate of this one. Please help with resolution of #429

**Comment by solomax** [comment] 2015-11-17 09:21
I believe the migration is done
Closing the issue

**Closed by solomax** 2015-11-17 09:21 UTC
