### ISSUE TITLE
GMap3 doesn't work after upgrade to 6.20

### ISSUE THREAD

**Issue by medvegy** [wicketstuff/core#413] opened 2015-07-08 06:54 UTC
GMap3 doesn't work after upgrade to 6.20
```
        <dependency>
            <groupId>org.wicketstuff</groupId>
            <artifactId>wicketstuff-gmap3</artifactId>
            <version>6.20.0</version>
        </dependency>
```
rendered source code says WicketMap is not defined. With 6.19 it works.
```
<!DOCTYPE html>
<html>
<head><script type="text/javascript" src="./wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-1.11.3.min-ver-895323ED2F7258AF4FAE2C738C8AEA49.js"></script>
    <script type="text/javascript" src="./wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-event-jquery.min-ver-CD167ED7BEFC26AED029F20C2EBF9AA7.js"></script>
    <script type="text/javascript" src="./wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-ajax-jquery.min-ver-373007567CBDD4D664471DD5DBA38759.js"></script>
    <script type="text/javascript" src="./wicket/resource/org.wicketstuff.gmap.WicketGMapJsReference/wicket-gmap-ver-D352798A5280EF1FF72FA02EE9817537.js"></script>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?v=3&sensor=false"></script>
    <script type="text/javascript" id="wicket-ajax-base-url">
        /*<![CDATA[*/
        Wicket.Ajax.baseUrl="contact";
        /*]]>*/
    </script>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Kontakt</title>

    <link rel="icon" type="image/ico" href="/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="/styles/styles-v1.adp.min.css" />
    <script type="text/javascript" >
        /*<![CDATA[*/
        Wicket.Event.add(window, "domready", function(event) {
            new WicketMap('map', false);
            Wicket.maps['map'].clearOverlays();
            Wicket.maps['map'].overlayListenerCallbackUrl = 'https://adp.ctoolkit.org/contact?50-1.IBehaviorListener.0-form-map';
            Wicket.maps['map'].setCenter(new google.maps.LatLng(48.1640315, 17.1489658, false));
            Wicket.maps['map'].setZoom(14);
            Wicket.maps['map'].setMinZoom(0);
            Wicket.maps['map'].setMaxZoom(0);
            Wicket.maps['map'].setDraggingEnabled(true);
            Wicket.maps['map'].setDoubleClickZoomEnabled(false);
            Wicket.maps['map'].setScrollWheelZoomEnabled(false);
            Wicket.maps['map'].setStreetViewControlEnabled(false);
            Wicket.maps['map'].setZoomControlEnabled(true);
            Wicket.maps['map'].setScaleControlEnabled(true);
            Wicket.maps['map'].setMapTypeControlEnabled(true);
            Wicket.maps['map'].setPanControlEnabled(true);
            Wicket.maps['map'].setMapType(google.maps.MapTypeId.ROADMAP);
            Wicket.maps['map'].addOverlay('overlay271', new google.maps.Marker({map: Wicket.maps['map'].map, position: new google.maps.LatLng(48.1640315, 17.1489658, false)}));
            Wicket.maps['map'].overlays['overlay271'].setMap(Wicket.maps['map'].map);
            ;
            Wicket.Event.publish(Wicket.Event.Topic.AJAX_HANDLERS_BOUND);
            ;});
        /*]]>*/
    </script>
</head>
<body></body>
</html>
```
Chrome console shows uncaught syntax error:
```
Uncaught ReferenceError: WicketMap is not defined
        (anonymous function) @ contact:25
        m.Callbacks.j @ jquery-1.11.3.min-ver-895323ED2F7258AF4FAE2C738C8AEA49.js:2
        m.Callbacks.k.fireWith @ jquery-1.11.3.min-ver-895323ED2F7258AF4FAE2C738C8AEA49.js:2
        m.extend.ready @ jquery-1.11.3.min-ver-895323ED2F7258AF4FAE2C738C8AEA49.js:2
        J @ jquery-1.11.3.min-ver-895323ED2F7258AF4FAE2C738C8AEA49.js:2
```

**Comment by martin-g** [comment] 2015-07-08 07:10
@JoachimRohde Ping!

**Comment by JoachimRohde** [comment] 2015-07-16 09:23
@medvegy Could you provide a quickstart project? I tried a quickstart project on my own and also tried out several examples from the GMap3-examples project of the wicket-6.x branch and cannot reproduce your problem. Everything was working as expected and also no error messages in the console log.

**Comment by JoachimRohde** [comment] 2015-07-30 21:32
@medvegy Does the error persist or can we close this issue?

**Comment by medvegy** [comment] 2015-07-31 17:06
Hi, please give me a little time to prepare some quickstart project. Thanks ;-)

**Comment by JoachimRohde** [comment] 2016-06-03 13:59
Since I could not reproduce this error and there was no feedback for almost a year, I close this issue.

**Closed by JoachimRohde** 2016-06-03 13:59 UTC
