### ISSUE TITLE
PackageScanner fails on Windows when Temp directory has spaces

### ISSUE THREAD

**Issue by arambau** [wicketstuff/core#380] opened 2015-02-01 03:50 UTC
It appears that the method for "private static Class<?>[] getClasses(String packageName)" is acquiring a URL that is incorrect on Windows 8. I think for JDK7, the file should referenced by taking the URL, retrieving the URI, then calling toFile(). Something like:

        while (resources.hasMoreElements()) {
            URL resource = resources.nextElement();
            try {
                File file = Paths.get(resource.toURI()).toFile();
                dirs.add(file);
            } catch (Exception ex) {
                // please implement better error handling;
            }

        }

URL returns something like:
C:\Users\John%20Doe\AppData\Local\Temp\jetty-0.0.0.0-9090-JavaScript_UI_Test.war-_JavaScript_UI_Test-any-9038450678738663760.dir\webapp\WEB-INF\classes\net\example\poc

This is not resolvable in Windows.

In its current form, it finds no classes because the directory is bogus.

**Comment by martin-g** [comment] 2015-02-01 12:29
Please send a Pull Request.
Thank you!

**Comment by martin-g** [comment] 2015-02-19 16:28
Closing because there was no action for 3 weeks.
If you believe that the issue is important enough to be part of the project then please create a Pull Request.
Thank you!

**Closed by martin-g** 2015-02-19 16:28 UTC
