### ISSUE TITLE
LazyModel used in ListView's populateItem can't detect target type

### ISSUE THREAD

**Issue by jan-krakora** [wicketstuff/core#572] opened 2017-01-27 23:33 UTC
I'm trying to use [LazyModel](https://github.com/wicketstuff/core/tree/master/wicketstuff-lazymodel) within a ListView, but it throws a ```WicketRuntimeException``` because the target type can not be detected.

Below is a test case simulating the problem.
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
		 
    <modelVersion>4.0.0</modelVersion>
        <groupId>test</groupId>
        <artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<dependencies>
	    <dependency>
		<groupId>org.wicketstuff</groupId>
		<artifactId>wicketstuff-lazymodel</artifactId>
		<version>7.0-SNAPSHOT</version>
	    </dependency>
	    <dependency>
		<groupId>org.wicketeer</groupId>
		<artifactId>wicket-modelfactory</artifactId>
		<version>7.9.16</version>
	    </dependency>
	    <dependency>
        	<groupId>javax.servlet</groupId>
        	<artifactId>javax.servlet-api</artifactId>
        	<version>3.0.1</version>
        	<scope>provided</scope>
	    </dependency>
	</dependencies>
	
	<build>
	    <plugins>
                <plugin>
	            <artifactId>maven-compiler-plugin</artifactId>
		    <version>3.3</version>
		    <configuration>
			<source>1.8</source>
			<target>1.8</target>
			<encoding>UTF-8</encoding>
		    </configuration>
		</plugin>
	    </plugins>
        </build>
	
	<repositories>
	    <repository>
	        <id>wicketstuff-core-snapshots</id>
		<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		<snapshots>
		    <enabled>true</enabled>
		</snapshots>
	    </repository>
	</repositories>
</project>
```
```java

import java.util.Arrays;
import java.util.List;

import org.apache.wicket.markup.html.list.ListItem;
import org.apache.wicket.markup.html.list.ListView;
import org.apache.wicket.model.IModel;
import org.apache.wicket.model.LoadableDetachableModel;
import org.apache.wicket.util.tester.WicketTester;
import org.junit.Assert;
import org.junit.Test;
import org.wicketeer.modelfactory.ModelFactory;
import org.wicketstuff.lazymodel.LazyModel;

public class TestCase {
	
    //*******************************************
    // Attributes
    //*******************************************
	
    private WicketTester wicketTester = new WicketTester();

    //*******************************************
    // Methods
    //*******************************************
	
    @Test
    public void modelFactoryTest() {
	IModel<List<Bean>> inputModel = new BeansModel();
	ListView<Bean> listView = new ListView<Bean>("dummy", inputModel) {
			
	    @Override
	    protected void populateItem(ListItem<Bean> item) {
		IModel<Bean> itemModel = item.getModel();
		IModel<Integer> valueModel = ModelFactory.model(ModelFactory.from(itemModel).getValue());
		Assert.assertEquals(Integer.valueOf(0), valueModel.getObject());
	    }
	};
	wicketTester.startComponentInPage(listView);
    }
	
    @Test
    public void lazyModelTest() {
	IModel<List<Bean>> inputModel = new BeansModel();
	ListView<Bean> listView = new ListView<Bean>("dummy", inputModel) {
			
	    @Override
	    protected void populateItem(ListItem<Bean> item) {
		IModel<Bean> itemModel = item.getModel();
		IModel<Integer> valueModel = LazyModel.model(LazyModel.from(itemModel).getValue());
		Assert.assertEquals(Integer.valueOf(0), valueModel.getObject());
	    }
	};
	wicketTester.startComponentInPage(listView);
    }
	
    //*******************************************
    // Inner classes
    //*******************************************
	
    public static class Bean {
		
	//*******************************************
	// Atributes
	//*******************************************
		
	private int value;

	//*******************************************
	// Getters / setters
	//*******************************************
		
	public int getValue() {
	    return value;
	}

	public void setValue(int value) {
	    this.value = value;
	}
		
    }
	
    public static class BeansModel extends LoadableDetachableModel<List<Bean>> {

	//*******************************************
	// Methods
	//*******************************************
		
	@Override
	protected List<Bean> load() {
	    return Arrays.asList(new Bean());
	}
		
    }

}
```
Tested on java 1.8.0_91. Result of lazyModelTest is
```
org.apache.wicket.WicketRuntimeException: cannot detect target type
	at org.wicketstuff.lazymodel.LazyModel.from(LazyModel.java:585)
	at TestCase$2.populateItem(TestCase.java:50)
	at org.apache.wicket.markup.html.list.ListView.onPopulate(ListView.java:523)
	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:124)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:950)
	at org.apache.wicket.Component.beforeRender(Component.java:1018)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1836)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3916)
	at org.apache.wicket.Page.onBeforeRender(Page.java:801)
	...
```
The same test with [wicket-modelfactory](https://github.com/uweschaefer/wicket-modelfactory) works perfectly. See modelFactoryTest.

**Comment by svenmeier** [comment] 2017-01-28 07:21
In this case there's no generic information left to derive the target type.

Note that wicket-modelfactory calls `#getObject()` as last resort (https://github.com/uweschaefer/wicket-modelfactory/blob/master/src/main/java/org/wicketeer/modelfactory/ModelFactory.java#L134).
This is not something we want LazyModel to do.

You can use `LazyModel.model(LazyModel.from(itemModel).getValue(), Bean.class);` instead. Or you could use a custom item model that carries generic information.

Closing as not a bug.

**Closed by svenmeier** 2017-01-28 07:21 UTC
